services:
  - type: web
    name: rockquest
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.8